remote_url = "urcs://urc-uefn.live.ucs.on.epicgames.com"
identity = "019ce6b3f9b4753fa48a4069783fd67e"

[store]
max_capacity = 10485760
eviction_delay = 10
max_size = 10737418240
compaction_delay = 30

[file]
direct_write = false
direct_io = false
flush_write = false
